name: stereoset

mode: experiment # experiment (creates predictions) or evaluation (computes scores)

## Experiment settings
persistent_dir: "/export/home/kraft/data/stereoset_data" # Directory where all persistent data will be stored.
batch_size: 1 # The batch size to use during StereoSet intrasentence evaluation.
seed: None # RNG seed. Used for logging in experiment ID.

## Evaluation settings